name: Build and Test
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Build
        working-directory: ./aoc
        run: go build -v 
      - name: Test with the Go CLI
        working-directory: ./aoc
        run: go test 

